"""Add incorrect answers to questions table

Revision ID: 3d46f2c5b993
Revises: 692d7bdb26a9
Create Date: 2025-07-08 04:41:22.332834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d46f2c5b993'
down_revision: Union[str, Sequence[str], None] = '692d7bdb26a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia_questions', sa.Column('incorrect_answer_1', sa.String(), nullable=False))
    op.add_column('trivia_questions', sa.Column('incorrect_answer_2', sa.String(), nullable=False))
    op.add_column('trivia_questions', sa.Column('incorrect_answer_3', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trivia_questions', 'incorrect_answer_3')
    op.drop_column('trivia_questions', 'incorrect_answer_2')
    op.drop_column('trivia_questions', 'incorrect_answer_1')
    # ### end Alembic commands ###
