"""Add google creds to user table

Revision ID: 47a8a7898151
Revises: 200f563c2999
Create Date: 2025-07-07 12:48:47.901422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a8a7898151'
down_revision: Union[str, Sequence[str], None] = '200f563c2999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_creds_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_creds_json')
    # ### end Alembic commands ###
