"""Add tmdb_id and genres to movie_history

Revision ID: 87e6e01ac296
Revises: 4e453e05ae26
Create Date: 2025-07-08 18:17:45.966946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87e6e01ac296'
down_revision: Union[str, Sequence[str], None] = '4e453e05ae26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_history', sa.Column('tmdb_id', sa.Integer(), nullable=False))
    op.add_column('movie_history', sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_history', 'genres')
    op.drop_column('movie_history', 'tmdb_id')
    # ### end Alembic commands ###
